// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sbbydmhcwieaotfqgipf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNiYnlkbWhjd2llYW90ZnFnaXBmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1ODYzNDUsImV4cCI6MjA2OTE2MjM0NX0.QuDJy9jqS5e5En0JcjNRrTtoqmdSl6LyG1HDI-AAe1o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});